[versions]

# Also change in build.gradle.kts
# resolutionStrategy when upgrading
configurate = "4.2.0-GeyserMC-SNAPSHOT"

scoreboard-library = "2.8.0"
adventure = "4.23.0"
placeholderapi = "2.12.2"
head-database-api = "1.3.2"

# Dependency downloaded at runtime, also change
# the version in AkropolisPluginLoader.java
# when upgrading
xseries = "13.7.1"

miniplaceholders = "3.1.0"
noteblockapi = "1.7.0"

[libraries]
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
scoreboard-library-api = { module = "net.megavex:scoreboard-library-api", version.ref = "scoreboard-library" }
scoreboard-library-implementation = { module = "net.megavex:scoreboard-library-implementation", version.ref = "scoreboard-library" }
adventure-bom = { module = "net.kyori:adventure-bom", version.ref = "adventure" }
adventure-api = { module = "net.kyori:adventure-api" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
head-database-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "head-database-api" }
xseries = { module = "com.github.cryptomorin:XSeries", version.ref = "xseries" }
miniplaceholders-api = { module = "io.github.miniplaceholders:miniplaceholders-api", version.ref = "miniplaceholders" }
noteblockapi  = { module = "com.github.koca2000:NoteBlockAPI", version.ref = "noteblockapi" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.4.3" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.21" }
